Fix weird unhandled runtime error
HOW
I imported App as import App from instead of
import { App } from.

WHAT THE ERROR SAID
Unhandled Runtime Error
Error: Element type is invalid: expected a string
(for built-in components) or a class/function (for composite components)
but got: undefined. You likely forgot to export your component from the
file it's defined in, or you might have mixed up default and named
imports.

Check the render method of `Home`.